# Install script for directory: C:/Users/kangmin/zephyrproject/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/Zephyr-Kernel")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2020-q4-major/bin/arm-none-eabi-objdump.exe")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/arch/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/lib/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/soc/arm/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/boards/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/subsys/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/drivers/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/cmsis/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/atmel/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/altera/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/canopennode/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/civetweb/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/espressif/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/fatfs/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/cypress/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/infineon/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/hal_nordic/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/openisa/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/nuvoton/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/microchip/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/silabs/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/st/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/stm32/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/ti/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/libmetal/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/quicklogic/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/lvgl/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/mbedtls/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/mcuboot/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/mcumgr/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/nxp/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/open-amp/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/loramac-node/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/openthread/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/segger/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/sof/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/tinycbor/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/tinycrypt/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/littlefs/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/mipi-sys-t/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/nrf_hw_models/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/xtensa/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/modules/trusted-firmware-m/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/kernel/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/cmake/flash/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/cmake/usage/cmake_install.cmake")
  include("C:/Users/kangmin/Documents/GitHub/Baby_monitor_wearable/Firmware/hello_world/nrf53dk/zephyr/cmake/reports/cmake_install.cmake")

endif()

